Enhancements
farhan-arshad-dev/recipe-management-app pull request #3
Opened 2019-05-30 07:47 UTC by farhan-arshad-dev

### Project code and feature Enhancements
- Integration of docker, travis-ci, and flake8.
- Added Unit test for the project feature. 
- Using TDD approach to create new feature. 
- Configure Postgresql.

2019-06-19 10:52 UTC, waheedahmed requested changes

2019-06-19 10:52 UTC, waheedahmed commented on docker-compose.yml
> +  db: # name of the service for the database
Move `db` at the top then you don't need `wait_for_db` command I believe.

2019-06-19 10:52 UTC, waheedahmed commented on .travis.yml
> +  - docker-compose run app sh -c "python recipe_management_project/manage.py test && flake8"
Always add a new line at end of file, add here and in other files too where missing.

2019-06-20 14:40 UTC, waheedahmed requested changes
Generally looks good, some small nits. Integerate Pylint and PEP8 and run them in travis build.

2019-06-20 14:40 UTC, waheedahmed commented on src/recipe_management_project/api/management/commands/wait_for_db.py
> +# 'time' use for the application sleep for some sec
Remove this command and related tests if not needed.

2019-06-20 14:40 UTC, waheedahmed commented on src/recipe_management_project/api/views.py
> +        is_already_following = following_models.FollowingModel.objects.\
nit: 
```
is_already_following = following_models.FollowingModel.objects.filter(
    following_to=following_to.id,
    following_by=self.request.user.id
)
```

2019-06-20 14:40 UTC, waheedahmed commented on src/recipe_management_project/api/views.py
> +        return following_models.FollowingModel.objects.\
Same here.

2019-06-21 06:53 UTC, farhan-arshad-dev commented
> Generally looks good, some small nits. Integerate Pylint and PEP8 and run them in travis build.

@waheedahmed after implementation of `Pylint`, are we need `flake8`?

2019-06-21 07:08 UTC, waheedahmed commented
@farhan-arshad-dev No, but do integerate PEP8 and also check `flake8` is correctly running during your build and reporting the voilations correctly if present.

2019-06-21 07:10 UTC, waheedahmed commented
I don't see any log present in your build saying anything related to if flake8 command ran successfully or not.

2019-06-21 07:21 UTC, farhan-arshad-dev commented
> @farhan-arshad-dev No, but do integerate PEP8 and also check `flake8` is correctly running during your build and reporting the voilations correctly if present.

flake8 is working fine, its show report if there is any error in the code.

2019-06-21 07:23 UTC, farhan-arshad-dev commented
> > Generally looks good, some small nits. Integerate Pylint and PEP8 and run them in travis build.
> 
> @waheedahmed after Integration of `Pylint`, are we need `flake8`?

Are we need to integrate the `Pylint` and `PEP8` (renamed as `pycodestyle`) in docker container?

2019-07-11 13:34 UTC, waheedahmed approved these changes

2019-07-15 07:57 UTC, merged